<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>no.entur.abt.bob.api</groupId>
    <artifactId>parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <name>participant-metadata-client</name>
  <artifactId>participant-metadata-client</artifactId>
  <description>participant-metadata-client</description>
  <version>0.0.1-SNAPSHOT</version>
  <url>https://github.com/entur/bob-openapi/clients/participant-metadata-client</url>
  <dependencies>
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
    </dependency>
    <dependency>
      <groupId>no.entur.abt.bob.api</groupId>
      <artifactId>participant-metadata-model</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>
                ${maven.multiModuleProjectDirectory}/models/participant-metadata-model/src/main/resources/model.yaml
              </inputSpec>
              <generatorName>java</generatorName>
              <configOptions>
                <sourceFolder>src/gen/java/main</sourceFolder>
                <useJakartaEe>true</useJakartaEe>
                <useSpringBoot3>true</useSpringBoot3>
              </configOptions>
              <!-- https://openapi-generator.tech/docs/generators/java/ -->
              <library>apache-httpclient</library>

              <generateApis>true</generateApis>
              <generateModels>false</generateModels>
              <generateSupportingFiles>true</generateSupportingFiles>

              <!-- Disable generation of test classes -->
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>

              <packageName></packageName>
              <apiPackage>no.entur.abt.bob.api.pm.client.api</apiPackage>
              <modelPackage>no.entur.abt.bob.api.pm.model</modelPackage>
              <invokerPackage>no.entur.abt.bob.api.pm.model.invoker</invokerPackage>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
