<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>no.entur.abt.bob.api</groupId>
  <artifactId>parent</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>BoB openapi parent</name>
  <description>parent</description>

  <url>https://github.com/entur/abt-bob-openapi</url>
  <organization>
    <name>Entur AS</name>
    <url>http://www.entur.org/</url>
  </organization>
  <licenses>
    <license>
      <name>EUPL-1.2</name>
      <url>https://joinup.ec.europa.eu/software/page/eupl</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

<developers>
    <developer>
        <name>Thomas Rørvik Skjølberg</name>
        <email>thomas.rorvik.skjolberg@entur.org</email>
        <organization>Entur</organization>
        <organizationUrl>http://www.entur.org</organizationUrl>
    </developer>
</developers>

  <scm>
    <connection>scm:git:ssh://git@github.com/entur/abt-bob-openapi.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/entur/abt-bob-openapi.git</developerConnection>
    <url>https://github.com/entur/abt-bob-openapi/tree/main</url>
    <tag>HEAD</tag>
  </scm>

  <properties>
    <apache-httpclient5.version>5.6</apache-httpclient5.version>
    <jackson.version>2.21.2</jackson.version>
    <jakarta.validation-api.version>3.1.1</jakarta.validation-api.version>
    <jakarta.annotation-api.version>3.0.0</jakarta.annotation-api.version>
    <jackson-databind-nullable.version>0.2.9</jackson-databind-nullable.version>
    <jreleaser-maven-plugin.version>1.23.0</jreleaser-maven-plugin.version>
    <junit.version>6.0.3</junit.version>
    <jsr305.version>3.0.2</jsr305.version>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <maven-javadoc-plugin.version>3.3.0</maven-javadoc-plugin.version>
    <maven-source-plugin.version>3.2.1</maven-source-plugin.version>
    <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <maven-deploy-plugin.version>3.1.4</maven-deploy-plugin.version>
    <maven-enforcer-plugin.version>3.6.2</maven-enforcer-plugin.version>
    <maven-javadoc-plugin.version>3.12.0</maven-javadoc-plugin.version>
    <maven-source-plugin.version>3.4.0</maven-source-plugin.version>
    <maven-surefire-plugin.version>3.5.5</maven-surefire-plugin.version>
    <openapi-generator-version>7.20.0</openapi-generator-version>
    <servlet-api.version>6.1.0</servlet-api.version>
    <spotless.version>3.3.0</spotless.version>
    <spring.version>6.2.12</spring.version>
    <swagger-annotations-version>1.6.16</swagger-annotations-version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${jackson.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>${jakarta.annotation-api.version}</version>
      </dependency>
      <dependency>
        <groupId>no.entur.abt.bob.api</groupId>
        <artifactId>participant-metadata-model</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.openapitools</groupId>
        <artifactId>jackson-databind-nullable</artifactId>
        <version>${jackson-databind-nullable.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.httpcomponents.client5</groupId>
        <artifactId>httpclient5</artifactId>
        <version>${apache-httpclient5.version}</version>
      </dependency>
      <dependency>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-annotations</artifactId>
        <version>${swagger-annotations-version}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.validation</groupId>
        <artifactId>jakarta.validation-api</artifactId>
        <version>${jakarta.validation-api.version}</version>
      </dependency>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-web</artifactId>
        <version>${spring.version}</version>
      </dependency>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-context</artifactId>
        <version>${spring.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.code.findbugs</groupId>
        <artifactId>jsr305</artifactId>
        <version>${jsr305.version}</version>
      </dependency>
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>${junit.version}</version>
      </dependency>
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>${junit.version}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.servlet</groupId>
        <artifactId>jakarta.servlet-api</artifactId>
        <version>${servlet-api.version}</version>
        <scope>provided</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.diffplug.spotless</groupId>
          <artifactId>spotless-maven-plugin</artifactId>
          <version>${spotless.version}</version>
          <executions>
            <execution>
              <goals>
                <goal>check</goal>
              </goals>
              <phase>validate</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <configuration>
            <source>${maven.compiler.source}</source>
            <target>${maven.compiler.target}</target>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.openapitools</groupId>
          <artifactId>openapi-generator-maven-plugin</artifactId>
          <version>${openapi-generator-version}</version>
        </plugin>
        <plugin>
          <groupId>org.jreleaser</groupId>
          <artifactId>jreleaser-maven-plugin</artifactId>
          <version>${jreleaser-maven-plugin.version}</version>
          <inherited>false</inherited>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven-deploy-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven-surefire-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${maven-javadoc-plugin.version}</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <detectJavaApiLink>false</detectJavaApiLink>
        </configuration>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <attach>true</attach>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${maven-enforcer-plugin.version}</version>
        <executions>
          <execution>
            <id>enforce-versions</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <bannedPlugins>
                  <!-- will only display a warning but does not fail the build. -->
                  <level>WARN</level>
                  <excludes>
                    <exclude>org.apache.maven.plugins:maven-verifier-plugin</exclude>
                  </excludes>
                  <message>Please consider using the maven-invoker-plugin (http://maven.apache.org/plugins/maven-invoker-plugin/)!</message>
                </bannedPlugins>
                <requireMavenVersion>
                  <version>3.6.3</version>
                </requireMavenVersion>
                <requireJavaVersion>
                  <version>1.8</version>
                </requireJavaVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.jreleaser</groupId>
        <artifactId>jreleaser-maven-plugin</artifactId>
        <configuration>
          <jreleaser>
            <signing>
              <active>ALWAYS</active>
              <armored>true</armored>
            </signing>
            <deploy>
              <maven>
                <mavenCentral>
                  <sonatype>
                    <active>RELEASE</active>
                    <url>https://central.sonatype.com/api/v1/publisher</url>
                    <stagingRepositories>target/staging-deploy</stagingRepositories>
                  </sonatype>
                </mavenCentral>
                <nexus2>
                  <maven-central>
                    <active>SNAPSHOT</active>
                    <url>https://ossrh-staging-api.central.sonatype.com/service/local</url>
                    <snapshotUrl>https://central.sonatype.com/repository/maven-snapshots</snapshotUrl>
                    <applyMavenCentralRules>true</applyMavenCentralRules>
                    <snapshotSupported>true</snapshotSupported>
                    <closeRepository>true</closeRepository>
                    <releaseRepository>true</releaseRepository>
                    <stagingRepositories>target/staging-deploy</stagingRepositories>
                  </maven-central>
                </nexus2>
              </maven>
            </deploy>
            <release>
              <github>
                <skipTag>false</skipTag>
                <skipRelease>true</skipRelease>
              </github>
            </release>
          </jreleaser>
        </configuration>
      </plugin>

    </plugins>
  </build>

  <profiles>
    <profile>
      <id>publication</id>
      <properties>
        <altDeploymentRepository>local::file:./target/staging-deploy</altDeploymentRepository>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>${maven-source-plugin.version}</version>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar</goal>
                </goals>
                <configuration>
                  <attach>true</attach>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <modules>
    <module>models/participant-metadata-model</module>
    <module>clients/participant-metadata-client</module>
    <module>servers/participant-metadata-server</module>
  </modules>

</project>
