<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>no.entur.abt.bob.api</groupId>
    <artifactId>parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <artifactId>participant-metadata-model</artifactId>
  <name>participant-metadata-model</name>
  <description>participant-metadata-model</description>
  <version>0.0.1-SNAPSHOT</version>
  <url>https://github.com/entur/bob-openapi/models/participant-metadata-model</url>
  <dependencies>
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
    </dependency>
    <!-- TODO Had to add provided scoped dep on jackson-jaxrs-json-provider as api clients are generated with an (unused?) import for JacksonJsonProvider even if useJakartaEe=true -->
    <dependency>
      <groupId>com.fasterxml.jackson.jaxrs</groupId>
      <artifactId>jackson-jaxrs-json-provider</artifactId>
      <scope>provided</scope>
    </dependency>

  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>
                ${maven.multiModuleProjectDirectory}/models/participant-metadata-model/src/main/resources/model.yaml
              </inputSpec>
              <generatorName>java</generatorName>
              <configOptions>
                <sourceFolder>src/gen/java/main</sourceFolder>
                <useSpringBoot3>false</useSpringBoot3>
                <useJakartaEe>true</useJakartaEe>
                <useBeanValidation>false</useBeanValidation>
                <annotationLibrary>none</annotationLibrary>
                <hideGenerationTimestamp>true</hideGenerationTimestamp>

              </configOptions>
              <!-- https://openapi-generator.tech/docs/generators/java/ -->
              <library>apache-httpclient</library>
              <generateApis>false</generateApis>
              <generateModels>true</generateModels>
              <generateSupportingFiles>false</generateSupportingFiles>

              <!-- Disable generation of test classes -->
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>

              <modelPackage>no.entur.abt.bob.api.pm.model</modelPackage>
              <invokerPackage>no.entur.abt.bob.api.pm.model.invoker</invokerPackage>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
